/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class PIN extends javax.swing.JFrame {

    /**
     * Creates new form PIN
     */
    public PIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfPIN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btenter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Masukkan PIN ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ATM Anda");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 70, 63, 10);

        tfPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPINActionPerformed(evt);
            }
        });
        getContentPane().add(tfPIN);
        tfPIN.setBounds(320, 120, 140, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\ATM_pinpad_in_german.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 290, 220);

        btenter.setText("Enter");
        btenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btenterActionPerformed(evt);
            }
        });
        getContentPane().add(btenter);
        btenter.setBounds(350, 160, 73, 23);

        setBounds(0, 0, 508, 356);
    }// </editor-fold>//GEN-END:initComponents

    private void btenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btenterActionPerformed
        // TODO add your handling code here:
        
        int pin=1234;
        if(pin==1234)
                 new TransaksiATM().setVisible(true);
                 dispose();
           
    }//GEN-LAST:event_btenterActionPerformed

    private void tfPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btenter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfPIN;
    // End of variables declaration//GEN-END:variables
}
