/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class ProgramAritmatika extends javax.swing.JFrame 
{
    
    String jns = "";
    int jml;

    /**
     * Creates new form ProgramAritmatika
     */
    public ProgramAritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bil4 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tvhasil = new javax.swing.JTextField();
        pilihanbil = new javax.swing.JComboBox<>();
        bhitung = new javax.swing.JButton();
        b4 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        getContentPane().setLayout(null);

        bil4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil4.setText("Bilangan 4");
        getContentPane().add(bil4);
        bil4.setBounds(50, 270, 110, 30);

        bil2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil2.setText("Bilangan 2");
        getContentPane().add(bil2);
        bil2.setBounds(50, 210, 110, 30);

        bil3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil3.setText("Bilangan 3");
        getContentPane().add(bil3);
        bil3.setBounds(50, 240, 110, 30);

        bil1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bil1.setText("Bilangan 1");
        getContentPane().add(bil1);
        bil1.setBounds(50, 180, 110, 30);

        jenis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(250, 70, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Aritmatika");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 70, 110, 30);

        panel.setBackground(new java.awt.Color(102, 255, 204));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        panel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Jumlah Bilangan");
        panel.add(jLabel1);
        jLabel1.setBounds(20, 40, 110, 30);

        tvhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvhasilActionPerformed(evt);
            }
        });
        panel.add(tvhasil);
        tvhasil.setBounds(200, 240, 140, 60);

        pilihanbil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(200, 50, 50, 20);

        bhitung.setText("HITUNG");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        panel.add(bhitung);
        bhitung.setBounds(220, 200, 90, 23);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        panel.add(b4);
        b4.setBounds(200, 170, 130, 20);

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        panel.add(b3);
        b3.setBounds(200, 140, 130, 20);

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        panel.add(b2);
        b2.setBounds(200, 110, 130, 20);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        panel.add(b1);
        b1.setBounds(200, 80, 130, 20);

        ket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ket.setText("jLabel3");
        panel.add(ket);
        ket.setBounds(140, 20, 100, 20);

        getContentPane().add(panel);
        panel.setBounds(30, 110, 360, 320);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PROGRAM ARITMATIKA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 20, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 460);

        setBounds(0, 0, 436, 493);
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void tvhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvhasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvhasilActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
       setJenis();
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText ("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
    
    }
    
    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                tvhasil.setText(""+ a1 + " + " + a2 + " + " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 + a2 + a3;
                tvhasil.setText(""+ a1 + " + " + a2 + " + " + a3 + " = " + hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                tvhasil.setText(""+ a1 + " + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }
        
        else if (jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                tvhasil.setText(""+ a1 + " - " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 - a2 - a3;
                tvhasil.setText(""+ a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                tvhasil.setText(""+ a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        
        else if (jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                tvhasil.setText(""+ a1 + " * " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 * a2 * a3;
                tvhasil.setText(""+ a1 + " * " + a2 + " * " + a3 + " = " + hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                tvhasil.setText(""+ a1 + " * " + a2 + " * " + a3 + " * " + a4 + " = " + hsl);
            }
        }
        
        else if (jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                tvhasil.setText(""+ a1 + " / " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 / a2 / a3;
                tvhasil.setText(""+ a1 + " / " + a2 + " / " + a3 + " = " + hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                tvhasil.setText(""+ a1 + " / " + a2 + " / " + a3 + " / " + a4 + " = " + hsl);
            }
        }
        
        
    }//GEN-LAST:event_bhitungActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed
    public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 2;
        }else if (pilihanbil.getSelectedItem().equals("3")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3;
        }else if(pilihanbil.getSelectedItem().equals("4")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
        }
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JButton bhitung;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField tvhasil;
    // End of variables declaration//GEN-END:variables

   
}
