
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class TransaksiATM extends javax.swing.JFrame {
    
     
        String str, str1;
        int choice,z,pin=1234,counter=0,a=3;
        int t,s,bal=50000;

    /**
     * Creates new form TransaksiATM
     */
    public TransaksiATM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Silahkan Pilih Transaksi Anda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 220, 30);

        jLabel2.setText("KELUAR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 210, 70, 14);

        jLabel3.setText("INFORMASI SALDO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 100, 120, 20);

        jLabel4.setText("PENYETORAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 100, 90, 14);

        jLabel5.setText("PENARIKAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 150, 90, 14);

        jLabel6.setText("PETUNJUK");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 150, 70, 14);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 90, 30, 30);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 100, 30, 30);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 140, 30, 30);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 200, 30, 30);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(350, 150, 30, 30);

        setBounds(0, 0, 436, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung   
                                        s = Integer.parseInt(str1); 
                                      
                                        setor1 hasil = new setor1();   
                                        hasil.menabung(bal, s);   
                                        bal=hasil.getsaldo();  

                                        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?",
                                                "ATM BNI SYARIAH-MAGETAN", 
                                                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain   
                                        if (z==0)
                                        {
                                            setVisible(true);
                                        } 
                                        else
                                            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda.");
                                         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
                                        t = Integer.parseInt(str1);
                                        tarik1 mengambil = new tarik1();
                                        mengambil.ambil(bal,t);
                                        bal =mengambil.getsaldo();
                                        
                                        z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?",
                                                "ATM BNI SYARIAH-MAGETAN",
                                                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
                                        if (z==0)
                                        {
                                            setVisible(true);
                                        }
                                        else
                                            
                                            JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BRI, ambil kartu ATM Anda.");
                                        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        JOptionPane.showMessageDialog(null,"Saldo Anda saat ini "
                                                + "sebesar : " + bal); //informasi saldo
                                        
                                        z=JOptionPane.showConfirmDialog(null,"Melanjutkan "
                                                + "transaksi lain?","ATM BNI SYARIAH-MAGETAN", 
                                                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
                                        if (z==0)   
                                        {
                                            setVisible(true);
                                        }
                                        else  
                                        
                                        JOptionPane.showMessageDialog(null,"Terimakasih telah "
                                                + "menggunakan ATM BNI SYARIAH - MAGETAN, ambil kartu ATM Anda.");
                                        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null,"Cara Penggunaan "
                                                + "Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah "
                                                + "dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan "
                                                + "dan rajinlah menabung\n ","INFO",1);
                                        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        z=JOptionPane.showConfirmDialog(null,"Anda ingin keluar?","Keluar",
                                                JOptionPane.YES_NO_OPTION, 0); 
 
                                        if (z==0){
                                            JOptionPane.showMessageDialog(null,"Terimakasih telah "
                                                    + "menggunakan ATM BNI SYARIAH, ambil kartu ATM Anda");
                                        System.exit(0);
                                        }
                                        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
